micronaut:
  application:
    name: micronautAwsLamdbaFunction

datasources:
  default:
    url: jdbc:postgresql://database.weipsdmsi.eu-central-1.rds.amazonaws.com/orders_db?characterEncoding=UTF-8
    username: postgres
    password: rootroot
    driverClassName: org.postgresql.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true