micronaut:
  application:
    name: micronautguide

datasources:
  default:
    url: jdbc:mysql://database-1.chiya2kvvqje.eu-central-1.rds.amazonaws.com:3306/ORDERS_DB?characterEncoding=UTF-8
    username: admin
    password: rootroot
    driverClassName: com.mysql.cj.jdbc.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect