micronaut:
  application:
    name: micronautguide

datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://database-1.chiya2kvvqje.eu-central-1.rds.amazonaws.com:3306/ORDERS_DB?characterEncoding=UTF-8`}
    username: ${JDBC_USER:admin}
    password: ${JDBC_PASSWORD:rootroot}
    driverClassName: com.mysql.cj.jdbc.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect