micronaut:
  application:
    name: micronautApp

datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/ORDERS_DB?characterEncoding=UTF-8`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect